@echo off
setlocal
set ROOT=%~dp0
pushd "%ROOT%"

REM Directories
for %%D in (
"public"
"public\assets"
"public\assets\images"
"public\assets\images\features"
"public\assets\images\testimonials"
"public\assets\images\onboarding"
"public\assets\images\illustrations"
"public\assets\icons"
"src"
"src\app"
"src\app\(marketing)"
"src\app\(marketing)\about"
"src\app\(marketing)\features"
"src\app\(marketing)\pricing"
"src\app\(marketing)\contact"
"src\app\(marketing)\blog"
"src\app\(marketing)\blog\[slug]"
"src\app\(auth)"
"src\app\(auth)\login"
"src\app\(auth)\register"
"src\app\(auth)\forgot-password"
"src\app\(auth)\reset-password"
"src\app\(app)"
"src\app\(app)\dashboard"
"src\app\(app)\appointments"
"src\app\(app)\tasks"
"src\app\(app)\calendar"
"src\app\(app)\meetings"
"src\app\(app)\settings"
"src\components"
"src\components\layout"
"src\components\ui"
"src\components\marketing"
"src\components\dashboard"
"src\components\appointments"
"src\components\tasks"
"src\components\calendar"
"src\components\meetings"
"src\components\settings"
"src\components\shared"
"src\hooks"
"src\lib"
"src\lib\types"
"src\lib\utils"
"src\lib\constants"
"src\lib\api"
"src\contexts"
"src\styles"
) do (
  if not exist "%%~D" mkdir "%%~D"
)

REM Files
for %%F in (
"public\favicon.ico"
"public\robots.txt"
"public\assets\images\logo.svg"
"public\assets\images\logo-white.svg"
"public\assets\images\hero-illustration.svg"
"public\assets\images\mockup-phone.png"
"public\assets\images\mockup-dashboard.png"
"public\assets\images\features\smart-scheduling.svg"
"public\assets\images\features\ai-assistant.svg"
"public\assets\images\features\analytics.svg"
"public\assets\images\features\collaboration.svg"
"public\assets\images\testimonials\avatar-1.jpg"
"public\assets\images\testimonials\avatar-2.jpg"
"public\assets\images\testimonials\avatar-3.jpg"
"public\assets\images\illustrations\empty-tasks.svg"
"public\assets\images\illustrations\no-meetings.svg"
"public\assets\images\illustrations\calendar-bg.svg"
"public\assets\icons\sprite.svg"

"src\app\layout.tsx"
"src\app\globals.css"
"src\app\page.tsx"
"src\app\(marketing)\about\page.tsx"
"src\app\(marketing)\features\page.tsx"
"src\app\(marketing)\pricing\page.tsx"
"src\app\(marketing)\contact\page.tsx"
"src\app\(marketing)\blog\page.tsx"
"src\app\(marketing)\blog\[slug]\page.tsx"
"src\app\(auth)\login\page.tsx"
"src\app\(auth)\register\page.tsx"
"src\app\(auth)\forgot-password\page.tsx"
"src\app\(auth)\reset-password\page.tsx"
"src\app\(app)\layout.tsx"
"src\app\(app)\dashboard\page.tsx"
"src\app\(app)\appointments\page.tsx"
"src\app\(app)\tasks\page.tsx"
"src\app\(app)\calendar\page.tsx"
"src\app\(app)\meetings\page.tsx"
"src\app\(app)\settings\page.tsx"

"src\components\layout\Navbar.tsx"
"src\components\layout\Footer.tsx"
"src\components\layout\AppNavbar.tsx"
"src\components\layout\BottomNav.tsx"
"src\components\layout\Sidebar.tsx"
"src\components\layout\PageWrapper.tsx"
"src\components\layout\Breadcrumbs.tsx"

"src\components\ui\Button.tsx"
"src\components\ui\Card.tsx"
"src\components\ui\Chip.tsx"
"src\components\ui\Toggle.tsx"
"src\components\ui\Modal.tsx"
"src\components\ui\ProgressRing.tsx"
"src\components\ui\ProgressBar.tsx"
"src\components\ui\Sparkline.tsx"
"src\components\ui\BarChart.tsx"
"src\components\ui\LineChart.tsx"
"src\components\ui\Badge.tsx"
"src\components\ui\Avatar.tsx"
"src\components\ui\AvatarGroup.tsx"
"src\components\ui\Skeleton.tsx"
"src\components\ui\Toast.tsx"
"src\components\ui\Dropdown.tsx"
"src\components\ui\Tabs.tsx"
"src\components\ui\Input.tsx"
"src\components\ui\Textarea.tsx"
"src\components\ui\Select.tsx"
"src\components\ui\Checkbox.tsx"
"src\components\ui\Radio.tsx"
"src\components\ui\DatePicker.tsx"
"src\components\ui\Container.tsx"

"src\components\marketing\Hero.tsx"
"src\components\marketing\HeroLeft.tsx"
"src\components\marketing\HeroRight.tsx"
"src\components\marketing\Features.tsx"
"src\components\marketing\FeatureCard.tsx"
"src\components\marketing\HowItWorks.tsx"
"src\components\marketing\StepCard.tsx"
"src\components\marketing\Testimonials.tsx"
"src\components\marketing\TestimonialCard.tsx"
"src\components\marketing\Pricing.tsx"
"src\components\marketing\PricingCard.tsx"
"src\components\marketing\Stats.tsx"
"src\components\marketing\CTASection.tsx"
"src\components\marketing\TrustedBy.tsx"
"src\components\marketing\BlogPreview.tsx"
"src\components\marketing\NewsletterSignup.tsx"

"src\components\dashboard\DashboardGrid.tsx"
"src\components\dashboard\WelcomeHeader.tsx"
"src\components\dashboard\KpiCard.tsx"
"src\components\dashboard\KpiGrid.tsx"
"src\components\dashboard\ProductivityChart.tsx"
"src\components\dashboard\TaskBreakdown.tsx"
"src\components\dashboard\UpcomingSchedule.tsx"
"src\components\dashboard\RecentActivity.tsx"
"src\components\dashboard\FocusTimer.tsx"
"src\components\dashboard\QuickStats.tsx"
"src\components\dashboard\CategoryDistribution.tsx"
"src\components\dashboard\StreakTracker.tsx"

"src\components\appointments\AppointmentsList.tsx"
"src\components\appointments\AppointmentCard.tsx"
"src\components\appointments\AppointmentFilters.tsx"
"src\components\appointments\AppointmentStatusBadge.tsx"
"src\components\appointments\AppointmentActions.tsx"
"src\components\appointments\AppointmentFormModal.tsx"
"src\components\appointments\AppointmentTypeSelector.tsx"
"src\components\appointments\AppointmentDurationPicker.tsx"
"src\components\appointments\CalendarHeatmap.tsx"
"src\components\appointments\UpcomingAppointments.tsx"

"src\components\tasks\TaskList.tsx"
"src\components\tasks\TaskCard.tsx"
"src\components\tasks\TaskFilters.tsx"
"src\components\tasks\AddTaskRow.tsx"
"src\components\tasks\TaskGroup.tsx"
"src\components\tasks\TaskFormModal.tsx"
"src\components\tasks\TaskPriorityBadge.tsx"
"src\components\tasks\TaskSearch.tsx"

"src\components\calendar\CalendarGrid.tsx"
"src\components\calendar\MonthHeader.tsx"
"src\components\calendar\WeekDaysRow.tsx"
"src\components\calendar\CalendarDay.tsx"
"src\components\calendar\AgendaList.tsx"
"src\components\calendar\AgendaItem.tsx"
"src\components\calendar\EventModal.tsx"
"src\components\calendar\CalendarViewToggle.tsx"

"src\components\meetings\MeetingCard.tsx"
"src\components\meetings\MeetingFilters.tsx"
"src\components\meetings\MeetingActions.tsx"
"src\components\meetings\MeetingAvatarGroup.tsx"
"src\components\meetings\JoinMeetingModal.tsx"

"src\components\settings\SettingsPanel.tsx"
"src\components\settings\SettingsGroup.tsx"
"src\components\settings\SettingRow.tsx"
"src\components\settings\ProfileBlock.tsx"
"src\components\settings\ThemeToggleRow.tsx"
"src\components\settings\NotificationSettings.tsx"
"src\components\settings\CalendarSyncSettings.tsx"
"src\components\settings\SignOutButton.tsx"

"src\components\shared\FilterPill.tsx"
"src\components\shared\PriorityDot.tsx"
"src\components\shared\TimeTag.tsx"
"src\components\shared\LocationTag.tsx"
"src\components\shared\StatusBadge.tsx"
"src\components\shared\EmptyState.tsx"
"src\components\shared\LoadingSpinner.tsx"
"src\components\shared\SearchBar.tsx"
"src\components\shared\ConfirmationDialog.tsx"
"src\components\shared\Logo.tsx"
"src\components\shared\ThemeSwitch.tsx"

"src\hooks\useTheme.ts"
"src\hooks\useLocalStorage.ts"
"src\hooks\useAuth.ts"
"src\hooks\useTasks.ts"
"src\hooks\useCalendar.ts"
"src\hooks\useMeetings.ts"
"src\hooks\useAppointments.ts"
"src\hooks\useDashboard.ts"
"src\hooks\useToast.ts"
"src\hooks\useMediaQuery.ts"
"src\hooks\useDebounce.ts"
"src\hooks\useAnalytics.ts"
"src\hooks\useScrollPosition.ts"

"src\lib\types\index.ts"
"src\lib\types\task.types.ts"
"src\lib\types\meeting.types.ts"
"src\lib\types\appointment.types.ts"
"src\lib\types\calendar.types.ts"
"src\lib\types\dashboard.types.ts"
"src\lib\types\user.types.ts"
"src\lib\types\auth.types.ts"
"src\lib\types\api.types.ts"

"src\lib\utils\cn.ts"
"src\lib\utils\date.ts"
"src\lib\utils\formatters.ts"
"src\lib\utils\priority.ts"
"src\lib\utils\appointment.ts"
"src\lib\utils\analytics.ts"

"src\lib\constants\navigation.ts"
"src\lib\constants\defaultSettings.ts"
"src\lib\constants\priorities.ts"
"src\lib\constants\appointmentStatus.ts"
"src\lib\constants\appointmentTypes.ts"
"src\lib\constants\features.ts"
"src\lib\constants\pricingPlans.ts"
"src\lib\constants\testimonials.ts"
"src\lib\constants\mockData.ts"

"src\lib\api\client.ts"
"src\lib\api\auth.ts"
"src\lib\api\tasks.ts"
"src\lib\api\meetings.ts"
"src\lib\api\appointments.ts"
"src\lib\api\dashboard.ts"
"src\lib\api\user.ts"

"src\contexts\ThemeContext.tsx"
"src\contexts\AuthContext.tsx"
"src\contexts\TasksContext.tsx"
"src\contexts\MeetingsContext.tsx"
"src\contexts\AppointmentsContext.tsx"
"src\contexts\CalendarContext.tsx"
"src\contexts\DashboardContext.tsx"
"src\contexts\ToastContext.tsx"

"src\middleware.ts"

"src\styles\fonts.css"
"src\styles\animations.css"
"src\styles\variables.css"

".env.local"
".env.example"
".eslintrc.json"
".prettierrc"
".gitignore"
"next.config.ts"
"package.json"
"postcss.config.mjs"
"tailwind.config.ts"
"tsconfig.json"
"README.md"
) do (
  if not exist "%%~F" type nul > "%%~F"
)

popd
endlocal
