import { Task, Meeting, Appointment, TaskStatus, TaskPriority } from '@/lib/types';

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    title: 'Morning Standup',
    description: 'Daily team sync meeting',
    project: 'Dev Team · Daily Sync',
    dueDate: new Date(2026, 2, 25, 9, 0),
    dueTime: '9:00 AM',
    priority: 'low' as TaskPriority,
    status: 'done' as TaskStatus,
    tags: ['meeting', 'daily'],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: '1',
    completedAt: new Date(2026, 2, 25, 9, 30),
  },
  {
    id: '2',
    title: 'Client Presentation',
    description: 'Quarterly review with ABC Corporation',
    project: 'ABC Corp · Q1 Review',
    dueDate: new Date(2026, 2, 25, 11, 30),
    dueTime: '11:30 AM',
    priority: 'high' as TaskPriority,
    status: 'in-progress' as TaskStatus,
    tags: ['client', 'presentation'],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: '1',
  },
  {
    id: '3',
    title: 'Project Review Session',
    description: 'Phase 3 review with the team',
    project: 'Sphere Team · Phase 3',
    dueDate: new Date(2026, 2, 25, 14, 0),
    dueTime: '2:00 PM',
    priority: 'medium' as TaskPriority,
    status: 'todo' as TaskStatus,
    tags: ['review', 'team'],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: '1',
  },
  {
    id: '4',
    title: 'Design Feedback Session',
    description: 'UI/UX review for mobile screens',
    project: 'Design Studio',
    dueDate: new Date(2026, 2, 25, 16, 30),
    dueTime: '4:30 PM',
    priority: 'medium' as TaskPriority,
    status: 'todo' as TaskStatus,
    tags: ['design', 'feedback'],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: '1',
  },
  {
    id: '5',
    title: 'Sprint Planning',
    description: 'Week 12 sprint planning',
    project: 'Engineering · Week 12',
    dueDate: new Date(2026, 2, 26, 9, 30),
    dueTime: '9:30 AM',
    priority: 'high' as TaskPriority,
    status: 'todo' as TaskStatus,
    tags: ['sprint', 'planning'],
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: '1',
  },
];

export const MOCK_MEETINGS: Meeting[] = [
  {
    id: '1',
    title: 'Client Presentation — Q1 Review',
    organization: 'ABC Corporation · Product Team',
    startTime: new Date(2026, 2, 25, 11, 30),
    endTime: new Date(2026, 2, 25, 13, 0),
    type: 'in-person',
    status: 'live',
    location: 'ABC Corp Office',
    participants: [
      { id: '1', name: 'Faris', email: 'faris@sphere.dev' },
      { id: '2', name: 'Jamie', email: 'jamie@abccorp.com' },
      { id: '3', name: 'Marcus', email: 'marcus@abccorp.com' },
    ],
    createdAt: new Date(),
    userId: '1',
  },
  {
    id: '2',
    title: 'Project Phase 3 Review',
    organization: 'Sphere Team · Engineering',
    startTime: new Date(2026, 2, 25, 14, 0),
    endTime: new Date(2026, 2, 25, 15, 0),
    type: 'video',
    status: 'upcoming',
    meetingLink: 'https://meet.sphere.app/phase3',
    participants: [
      { id: '1', name: 'Faris', email: 'faris@sphere.dev' },
      { id: '4', name: 'Kai', email: 'kai@sphere.dev' },
      { id: '5', name: 'Lena', email: 'lena@sphere.dev' },
    ],
    createdAt: new Date(),
    userId: '1',
  },
  {
    id: '3',
    title: 'Morning Standup',
    organization: 'Dev Team · Daily Sync',
    startTime: new Date(2026, 2, 25, 9, 0),
    endTime: new Date(2026, 2, 25, 9, 30),
    type: 'in-person',
    status: 'done',
    location: 'Conference Room A',
    participants: [
      { id: '1', name: 'Faris', email: 'faris@sphere.dev' },
      { id: '6', name: 'Maya', email: 'maya@sphere.dev' },
    ],
    createdAt: new Date(),
    userId: '1',
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: '1',
    title: 'Client Onboarding Call',
    description: 'Introduction and platform walkthrough',
    startTime: new Date(2026, 2, 25, 9, 0),
    endTime: new Date(2026, 2, 25, 9, 30),
    duration: 30,
    type: 'onboarding',
    status: 'completed',
    location: 'Video Call',
    meetingLink: 'https://meet.sphere.app/onboarding',
    clientName: 'Sarah Mitchell',
    clientEmail: 'sarah@client.com',
    createdAt: new Date(),
    userId: '1',
  },
  {
    id: '2',
    title: 'Quarterly Business Review',
    description: 'Q1 performance review',
    startTime: new Date(2026, 2, 25, 11, 30),
    endTime: new Date(2026, 2, 25, 13, 0),
    duration: 90,
    type: 'business',
    status: 'in-progress',
    location: 'ABC Corp HQ',
    clientName: 'ABC Corporation',
    clientEmail: 'contact@abccorp.com',
    createdAt: new Date(),
    userId: '1',
  },
  {
    id: '3',
    title: '1:1 Mentorship Session',
    description: 'Career development discussion',
    startTime: new Date(2026, 2, 25, 14, 0),
    endTime: new Date(2026, 2, 25, 15, 0),
    duration: 60,
    type: 'mentoring',
    status: 'scheduled',
    location: 'Zoom',
    meetingLink: 'https://zoom.us/j/123456',
    clientName: 'James Okoye',
    clientEmail: 'james@mentee.com',
    createdAt: new Date(),
    userId: '1',
  },
];